// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalSite.Data;

#nullable disable

namespace MyPersonalSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820010644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("MyPersonalSite.Shared.Models.ResumeItemBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResumeItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("ResumeItemBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyPersonalSite.Shared.Models.ResumeSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResumeSections");
                });

            modelBuilder.Entity("MyPersonalSite.Shared.Models.Milestone", b =>
                {
                    b.HasBaseType("MyPersonalSite.Shared.Models.ResumeItemBase");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Milestone");
                });

            modelBuilder.Entity("MyPersonalSite.Shared.Models.ResumeEntry", b =>
                {
                    b.HasBaseType("MyPersonalSite.Shared.Models.ResumeItemBase");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResumeSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasIndex("ResumeSectionId");

                    b.HasDiscriminator().HasValue("ResumeEntry");
                });

            modelBuilder.Entity("MyPersonalSite.Shared.Models.Skill", b =>
                {
                    b.HasBaseType("MyPersonalSite.Shared.Models.ResumeItemBase");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Skill");
                });

            modelBuilder.Entity("MyPersonalSite.Shared.Models.ResumeEntry", b =>
                {
                    b.HasOne("MyPersonalSite.Shared.Models.ResumeSection", null)
                        .WithMany("Entries")
                        .HasForeignKey("ResumeSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("MyPersonalSite.Shared.Models.BulletPoint", "BulletPoints", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ResumeEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("TEXT")
                                .HasColumnName("BulletPoint");

                            b1.HasKey("Id");

                            b1.HasIndex("ResumeEntryId");

                            b1.ToTable("ResumeEntryBulletPoints", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ResumeEntryId");
                        });

                    b.Navigation("BulletPoints");
                });

            modelBuilder.Entity("MyPersonalSite.Shared.Models.ResumeSection", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
